action_dim=10
agent_pos_dim=10
augmentation_pcd=false
augmentation_rot=false
augmentation_scale=false
batch_size=16
checkpoint_every=2
dense_pcd_for_goal=false
encoder_type=act3d
# encoding_modes: "keep_position_feature_in_attention_feature" 
encoding_mode="keep_position_feature_in_attention_feature_with_gripper_displacement_to_closest_object"
encoder_output_dim=60
final_attention=false
goal_mode=cross_attention_to_goal
horizon=8
in_channels=3
is_pickle=true
kept_in_disk=true
load_per_step=true
max_steps=35
n_obs_steps=2
normalize_action=true
num_load_episodes=75 # 10 for debugging, 1000 for training
observation_mode='dp3_goal_gripper_dense' # 'act3d_goal_mlp_displacement_gripper_to_object'
only_handle_points=false
pc_channel=3 # we should modify this
pointcloud_backbone='mlp'
pointcloud_num=4500
prediction_target=action
rollout_every=50
scale_scene_by_pcd=false
self_attention=false
time_stamp=$(date +%m%d%H%M)
train_ratio=1.0 # for generalization
training_epoches=31
use_absolute_waypoint=false
use_attn_for_point_features=false
use_joint_angle=0
use_lightweight_unet=0
use_mlp=1
use_pretrained_high_level_policy_as_low_level_input=true
use_segmask=0

# this has to be last
exp_name="${time_stamp}-${observation_mode}-horizon-${horizon}-num_load_episodes-${num_load_episodes}"
