wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.15.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1742481533.761202
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 23
      4: 3.9.16
      5: 0.15.4
      8:
      - 5
output_dir:
  desc: null
  value: ./high_level/pointnet2_super_model_invariant_2025-03-20_use_75_episodes_200-obj_paper_1211
model_type:
  desc: null
  value: pointnet2_super
lr:
  desc: null
  value: 0.001
weight_loss_weight:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 50
all_zarr_path:
  desc: null
  value: null
num_train_objects:
  desc: null
  value: '200'
dataset_prefix:
  desc: null
  value: /media/chenyuan/7e1e609b-387d-4a95-9219-2535fbbecfe9/articubot_demo/dp3_demo
beg_ratio:
  desc: null
  value: 0
end_ratio:
  desc: null
  value: 1
num_epochs:
  desc: null
  value: 60
save_freq:
  desc: null
  value: 2
only_first_stage:
  desc: null
  value: false
exp_path:
  desc: null
  value: ./high_level/pointnet2_super_model_invariant_2025-03-20_use_75_episodes_200-obj_paper_1211
load_model_path:
  desc: null
  value: null
output_obj_pcd_only:
  desc: null
  value: false
use_all_data:
  desc: null
  value: false
use_combined_action:
  desc: null
  value: false
model_invariant:
  desc: null
  value: true
predict_two_goals:
  desc: null
  value: false
keep_gripper_in_fps:
  desc: null
  value: 0
add_one_hot_encoding:
  desc: null
  value: 0
using_weight:
  desc: null
  value: 1
exp_name:
  desc: null
  value: _paper_1211
