export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib/nvidia
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/pbhowal/.mujoco/mujoco210/bin


PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:$PYTHONPATH MUJOCO_GL=egl DISPLAY=:99 python external/mimicgen/mimicgen/scripts/convert_dataset.py --input /scratch/pbhowal/Uncertainty_Dataset/Original_Dataset/mug_cleanup_d1.hdf5 --output_dir /scratch/pbhowal/Uncertainty_Dataset/test_output_with_curvature_005_curvature_minseg_20/ --camera_height 256 --camera_width 256 --num_workers 32 --curvature_threshold 0.05 --min_segment_len 20



PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:$PYTHONPATH MUJOCO_GL=egl DISPLAY=:99 python external/mimicgen/mimicgen/scripts/convert_dataset.py --input /scratch/pbhowal/Uncertainty_Dataset/Original_Dataset/mug_cleanup_d1.hdf5 --output_dir /scratch/pbhowal/Uncertainty_Dataset/test_output_bocpd/ --camera_height 256 --camera_width 256 --num_workers 1 --use_bayesian_decomp --bocpd_config third_party/robogen/bocpd_config.yaml --n 2



PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:$PYTHONPATH MUJOCO_GL=egl DISPLAY=:99 python external/mimicgen/mimicgen/scripts/convert_dataset.py --input /scratch/pbhowal/Uncertainty_Dataset/Original_Dataset/coffee_d0.hdf5 --output_dir /scratch/pbhowal/Uncertainty_Dataset/test_COFFEE_output_bocpd_use_only_jerk_and_curve_CHECK --camera_height 256 --camera_width 256 --num_workers 32 --use_bayesian_decomp --bocpd_config third_party/robogen/bocpd_config_COFFEE_FINAL.yaml


PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:$PYTHONPATH MUJOCO_GL=egl DISPLAY=:99 python external/mimicgen/mimicgen/scripts/convert_dataset.py --input /scratch/pbhowal/Uncertainty_Dataset/Original_Dataset/coffee_d0.hdf5 --output_dir /scratch/pbhowal/Uncertainty_Dataset/test_COFFEE_output_bocpd_use_only_jerk_and_curve_CHECK --camera_height 256 --camera_width 256 --num_workers 32 --pool_size 8 --use_bayesian_decomp --bocpd_config third_party/robogen/bocpd_config_COFFEE_FINAL.yaml


PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:$PYTHONPATH MUJOCO_GL=egl DISPLAY=:99 python external/mimicgen/mimicgen/scripts/convert_dataset.py --input /scratch/pbhowal/Uncertainty_Dataset/Original_Dataset/coffee_preparation_d0.hdf5 --output_dir /scratch/pbhowal/Uncertainty_Dataset/test_COFFEE_PREPERATION_output_bocpd_use_only_jerk_and_curve  --camera_height 256 --camera_width 256 --num_workers 1 --pool_size 1 --use_bayesian_decomp --bocpd_config third_party/robogen/bocpd_config_COFFEE_PREPERATION.yaml


PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:$PYTHONPATH MUJOCO_GL=egl DISPLAY=:99 python external/mimicgen/mimicgen/scripts/convert_dataset.py --input /scratch/pbhowal/Uncertainty_Dataset/Original_Dataset/kitchen_d0.hdf5 --output_dir /scratch/pbhowal/Uncertainty_Dataset/test_KITCHEN_output_bocpd_use_only_jerk_and_curve  --camera_height 256 --camera_width 256 --num_workers 1 --pool_size 1 --use_bayesian_decomp --bocpd_config third_party/robogen/bocpd_config_kitchen.yaml
PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:$PYTHONPATH MUJOCO_GL=egl DISPLAY=:99 python external/mimicgen/mimicgen/scripts/convert_dataset.py --input /scratch/pbhowal/Uncertainty_Dataset/Original_Dataset/kitchen_d0.hdf5 --output_dir ./test_KITCHEN_output_bocpd_use_only_jerk_and_curve_CHECK  --camera_height 256 --camera_width 256 --num_workers 1 --pool_size 1 --use_bayesian_decomp --bocpd_config third_party/robogen/bocpd_config_kitchen.yaml --n 2

~/.pixi/bin/pixi run 


PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:$PYTHONPATH MUJOCO_GL=egl DISPLAY=:99 ~/.pixi/bin/pixi run python real_world/run_gmm_on_dataset.py --dataset_dir /scratch/pbhowal/Uncertainty_Dataset/test_COFFEE_output_bocpd_use_only_jerk_and_curve_CHECK --high_level_ckpt_path ../../SMITH_High_Level_FineTune/exps/2026-04-27finetune_mug_cleanup/model_25001.pth --cat_idx 0 --max_files 1 --max_timesteps 89 --one_hot_encoding 1 --visualize --visualize_all_gmm_goals

MUJOCO_GL=egl DISPLAY=:99 ~/.pixi/bin/pixi run bash -c 'PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference/3d_diffusion_policy/3D-Diffusion-Policy/3D-Diffusion-Policy:$PYTHONPATH python run_gmm_on_dataset.py --dataset_dir /scratch/pbhowal/Uncertainty_Dataset/test_output_with_curvature_005_curvature_minseg_20/ --high_level_ckpt_path ../../SMITH_High_Level_FineTune/exps/2026-04-27finetune_mug_cleanup/model_95001.pth --siglip_path /project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code/RoboGen-sim2real/siglip_text_features_w_pick_and_place_w_grasp_and_lift.pt --cat_idx 0 --max_files 1 --one_hot_encoding 0 --visualize_all_gmm_goals --visualize'


MUJOCO_GL=egl DISPLAY=:99 ~/.pixi/bin/pixi run bash -c 'PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference/3d_diffusion_policy/3D-Diffusion-Policy/3D-Diffusion-Policy:$PYTHONPATH python run_gmm_on_dataset.py --dataset_dir /scratch/pbhowal/LOW_LEVEL_TRAIN_DATASET_SMITH_STYLE_DATASET/test_KITCHEN_output_bocpd_use_only_jerk_and_curve/ --high_level_ckpt_path ../../SMITH_High_Level_FineTune/exps/2026-04-27finetune_kitchen/model_95001.pth --siglip_path /project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code/RoboGen-sim2real/siglip_text_features_w_pick_and_place_w_grasp_and_lift.pt --cat_idx 0 --max_files 1 --one_hot_encoding 0 --visualize_all_gmm_goals --visualize'
       
MUJOCO_GL=egl DISPLAY=:99 ~/.pixi/bin/pixi run bash -c 'PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference/3d_diffusion_policy/3D-Diffusion-Policy/3D-Diffusion-Policy:$PYTHONPATH python run_gmm_on_dataset.py --dataset_dir /scratch/pbhowal/Uncertainty_Dataset/test_COFFEE_output_bocpd_use_only_jerk_and_curve_CHECK/ --high_level_ckpt_path ../../SMITH_High_Level_FineTune/exps/2026-04-27finetune_coffee_task/model_95001.pth --siglip_path /project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code/RoboGen-sim2real/siglip_text_features_w_pick_and_place_w_grasp_and_lift.pt --cat_idx 0 --max_files 1 --one_hot_encoding 0 --visualize_all_gmm_goals --visualize'

##### NO GMM DATASET GENERATION ########

MUJOCO_GL=egl DISPLAY=:99 ~/.pixi/bin/pixi run bash -c 'PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference/3d_diffusion_policy/3D-Diffusion-Policy/3D-Diffusion-Policy:$PYTHONPATH python run_gmm_on_dataset.py --dataset_dir /scratch/pbhowal/Uncertainty_Dataset/test_COFFEE_output_bocpd_use_only_jerk_and_curve_CHECK/ --no_gmm --no_gmm_output_dir /scratch/pbhowal/Uncertainty_Dataset/test_COFFEE_output_bocpd_use_only_jerk_and_curve_CHECK_NO_GMM'

MUJOCO_GL=egl DISPLAY=:99 ~/.pixi/bin/pixi run bash -c 'PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference/3d_diffusion_policy/3D-Diffusion-Policy/3D-Diffusion-Policy:$PYTHONPATH python run_gmm_on_dataset.py --dataset_dir /scratch/pbhowal/Uncertainty_Dataset/test_output_with_curvature_005_curvature_minseg_20/ --no_gmm --no_gmm_output_dir /project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_High_Level_FineTune/LOW_LEVEL_NO_GMM_DATASET/test_output_with_curvature_005_curvature_minseg_20/'

MUJOCO_GL=egl DISPLAY=:99 ~/.pixi/bin/pixi run bash -c 'PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference/3d_diffusion_policy/3D-Diffusion-Policy/3D-Diffusion-Policy:$PYTHONPATH python run_gmm_on_dataset.py --dataset_dir /scratch/pbhowal/Uncertainty_Dataset/test_KITCHEN_output_bocpd_use_only_jerk_and_curve/ --no_gmm --no_gmm_output_dir /project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_High_Level_FineTune/LOW_LEVEL_NO_GMM_DATASET/test_KITCHEN_output_bocpd_use_only_jerk_and_curve_NO_GMM/'

MUJOCO_GL=egl DISPLAY=:99 ~/.pixi/bin/pixi run bash -c 'PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference/3d_diffusion_policy/3D-Diffusion-Policy/3D-Diffusion-Policy:$PYTHONPATH python run_gmm_on_dataset.py --dataset_dir /scratch/pbhowal/Uncertainty_Dataset/test_COFFEE_PREPERATION_output_bocpd_use_only_jerk_and_curve/ --no_gmm --no_gmm_output_dir /project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_High_Level_FineTune/LOW_LEVEL_NO_GMM_DATASET/test_COFFEE_PREPERATION_output_bocpd_use_only_jerk_and_curve_NO_GMM/'



# GMM DEBUG VISUALIZATION 

MUJOCO_GL=egl DISPLAY=:99 ~/.pixi/bin/pixi run bash -c 'PYTHONPATH=/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/SMITH_MimicGen/SMITH_on_mimicgen/external/robomimic:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference:/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code_FINAL/cleaned_smith_real_world_inference/3d_diffusion_policy/3D-Diffusion-Policy/3D-Diffusion-Policy:$PYTHONPATH python run_gmm_on_dataset.py --dataset_dir ../../SMITH_High_Level_FineTune/HIGH_LEVEL_GMM_DEBUG_DATASET/Coffee_Task/ --high_level_ckpt_path ../../SMITH_High_Level_FineTune/exps/2026-04-29debug_gmm_coffee/model_12501.pth --siglip_path /project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/Articubot_Data_For_RVT/Yufei_Data_Generation_Code/RoboGen-sim2real/siglip_text_features_w_pick_and_place_w_grasp_and_lift.pt --cat_idx 0 --max_files 1 --one_hot_encoding 0 --visualize_all_gmm_goals --visualize'


