#!/bin/bash

#SBATCH -N 1 # Number of nodes
#SBATCH -n 12
#SBATCH -p ROBO
#SBATCH --gpus=h100:1 #GPU specification. H100
#SBATCH -t 48:00:00 # Estimated time, 48hour max. DD-HH:MM.
#SBATCH --job-name test # 50-obj-act3d-unet-low-level-with-goal
#SBATCH -o sbatch_output/job_%j.out
#SBATCH -e sbatch_output/job_%j.err
#SBATCH --mail-type=END
#SBATCH --mail-user=chialiak@andrew.cmu.edu

# use the bash shell
set -x 
# echo each command to standard out before running it


### first copy all the data needed in parallel
# Define an array of source-destination pairs
# "${source_dir}/debug:/local/"
# "/ocean/projects/cis240052p/ckuo1/RoboGen-sim2real/one_traj/0622-act3d-obj-45448-remove-reaching-collision-resize-2-full-per-step-gripper-goal-displacement-to-closest-obj-point:/local/"
# "/jet/projects/cis240052p/ywang59/dp3_demo/0622-act3d-obj-45448-remove-reaching-collision-resize-2-full-per-step-gripper-goal-displacement-to-closest-obj-point/2024-05-11-14-17-04:/local/"
source_dir="/jet/projects/cis240052p/ywang59/dp3_demo"
# declare -a SOURCES=(
#     "${source_dir}/0622-act3d-obj-45448-remove-reaching-collision-resize-2-full-per-step-gripper-goal-displacement-to-closest-obj-point:/local/"
#     # Add more source-destination pairs as needed
# )

# # Start the timer
# SECONDS=0

# # Function to run rsync command
# run_rsync() {
#     local src="$1"
#     local dst="$2"
#     rsync -az "$src" "$dst" &
# }

# # Loop through the array and run rsync commands in parallel
# for pair in "${SOURCES[@]}"; do
#     IFS=":" read -r src dst <<< "$pair"
#     run_rsync "$src" "$dst"
# done

# # Wait for all background processes to complete
# wait

# echo "All rsync commands have completed."
# total_time=$SECONDS
# echo "Total time taken: $(($total_time / 60)) minutes and $(($total_time % 60)) seconds."

#### start training
singularity exec --bind /ocean/projects/cis240052p/ckuo1/RoboGen-sim2real:/mnt/RoboGen_sim2real/ --bind /local/:/local/ --nv /ocean/projects/cis240052p/ywang59/robogen-dp3-act3d.sif /mnt/RoboGen_sim2real/run-in-singularity-pickle-debug.sh
