exp_id: rvt2_restart_slide_block_to_color_target_reload_ckpt_2_DEBUG_FOR_DATASET_GEN  #rvt2_restart_put_groceries_in_cupboard_reload_ckpt #
tasks: slide_block_to_color_target #push_buttons #place_shape_in_shape_sorter #light_bulb_in #close_jar #place_cups #place_wine_at_rack_location #meat_off_grill #sweep_to_dustpan_of_size #stack_blocks #sweep_to_dustpan_of_size #reach_and_drag #put_item_in_drawer #put_groceries_in_cupboard #open_drawer #put_money_in_safe #insert_onto_square_peg #put_groceries_in_cupboard #open_drawer   #put_money_in_safe #insert_onto_square_peg
bs: 8
num_workers: 0
epochs: 101
resume: "/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/RVT2_GMM_Codebase/RVT2_Codebase/RVT/runs/rvt2_original_trained/model_99.pth" #"/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/RVT2_GMM_Codebase/RVT2_Codebase/RVT/runs/rvt2_restart_insert_onto_square_peg_reload_ckpt/model_99.pth" #/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/RVT2_GMM_Codebase/RVT2_Codebase/RVT/runs/rvt2_original_trained/model_99.pth
sample_distribution_mode: task_uniform
peract:
  lr: 1.25e-5
  warmup_steps: 2000
  optimizer_type: lamb
  lr_cos_dec: True
  transform_augmentation_xyz: [0 ,0, 0] #[0.125, 0.125, 0.125]
  transform_augmentation_rpy: [0, 0, 0] #[0.0, 0.0, 45.0]
  amp: True
  bnb: True
  lambda_weight_l2: 1e-4
rvt:
  place_with_mean: False
  img_aug: 0.0
