defaults:
    - sac

agent_name: sac

env: cheetah_run

# this needs to be specified manually
experiment: test_exp

num_train_steps: 150250
replay_buffer_capacity: ${num_train_steps}

num_seed_steps: 20000

eval_frequency: 10000
num_eval_episodes: 2

device: cuda

# logger
log_frequency: 10000
log_save_tb: true

# video recorder
save_video: true

num_env: 2

seed: 1

task_config_path: None
solution_path: None
substep: None
final_state_path: None
rl_save_path: None
time_limit: 


# hydra configuration
hydra:
    run:
        dir: ./