name: high_level_heatmap_cnn_zarr_dataloader_EARLY_PUSH_BUTTONS
######## 3 VARIATIONS => 1st variation => 1 ENCODER WITH 19 CHANNELS (RGBD * 4 + 3 HEATMAPS) ############
# image_shape: &image_shape [19, 128, 128]
# ######## 3 VARIATIONS => 2nd variation (Early Fusion Architecture)=> 4 ENCODER WITH 5 CHANNELS FOR VIRTUAL CAMERA AND 4 CHANNEL FOR WRIST CAMERA ############
image_shape: &image_shape [5, 128, 128] #19 # 15
wrist_image_shape: &wrist_image_shape [4, 128, 128]
######## 3 VARIATIONS => 3rd variation (Late Fusion Architecture)=> 4 ENCODER WITH 5 CHANNELS FOR VIRTUAL CAMERA AND 4 CHANNEL FOR WRIST CAMERA ############
# image_shape: &image_shape [4, 128, 128] #19 # 15
# heatmap_image_shape: &heatmap_image_shape [1, 128, 128]

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim
  # obs:
  #   agentview_image:
  #     shape: [15, 128, 128]
  #     type: rgb
  #   robot0_eye_in_hand_image:
  #     shape: [15, 128, 128]
  #     type: rgb
  #   robot0_eef_pos:
  #     shape: [3]
  #     # type default: low_dim
  #   robot0_eef_quat:
  #     shape: [4]
  #   robot0_gripper_qpos:
  #     shape: [2]
  # action: 
  #   shape: [8]
  ######## 3 VARIATIONS => 1st variation => 1 ENCODER WITH 19 CHANNELS (RGBD * 4 + 3 HEATMAPS) ############
  # obs:
  #   image_cam:
  #       shape: *image_shape
  #       type: rgb
  ######## 3 VARIATIONS => 2nd variation (Early Fusion Architecture)=> 4 ENCODER WITH 5 CHANNELS FOR VIRTUAL CAMERA AND 4 CHANNEL FOR WRIST CAMERA ############
  obs:
    image_cam1:
      shape: *image_shape
      type: rgb
    image_cam2:
      shape: *image_shape
      type: rgb
    image_cam3:
      shape: *image_shape
      type: rgb
    image_cam4:
      shape: *wrist_image_shape
      type: rgb
    agent_pos:
      shape: [8]
      type: low_dim
  action:
    shape: [8]
  ######## 3 VARIATIONS => 3rd variation (Late Fusion Architecture)=> 7 ENCODER, SEPERATE ENCODERS FOR RGBD AND HEATMAPS ############
  # obs:
  #   image_cam1:
  #     shape: *image_shape
  #     type: rgb
  #   image_cam2:
  #     shape: *image_shape
  #     type: rgb
  #   image_cam3:
  #     shape: *image_shape
  #     type: rgb
  #   image_cam4:
  #     shape: *image_shape
  #     type: rgb
  #   image_cam5:
  #     shape: *heatmap_image_shape
  #     type: rgb
  #   image_cam6:
  #     shape: *heatmap_image_shape
  #     type: rgb
  #   image_cam7:
  #     shape: *heatmap_image_shape
  #     type: rgb
  #   agent_pos:
  #     shape: [8]
  #     type: low_dim
  # action:
  #   shape: [8]

    

# task_name: &task_name lift
# dataset_type: &dataset_type ph
# dataset_path: &dataset_path data/robomimic/datasets/${task.task_name}/${task.dataset_type}/image_abs.hdf5
# abs_action: &abs_action True

# env_runner:
#   _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
#   dataset_path: *dataset_path
#   shape_meta: *shape_meta
#   n_train: 6
#   n_train_vis: 2
#   train_start_idx: 0
#   n_test: 50
#   n_test_vis: 4
#   test_start_seed: 100000
#   # use python's eval function as resolver, single-quoted string as argument
#   max_steps: ${eval:'500 if "${task.dataset_type}" == "mh" else 400'}
#   n_obs_steps: ${n_obs_steps}
#   n_action_steps: ${n_action_steps}
#   render_obs_key: 'agentview_image'
#   fps: 10
#   crf: 22
#   past_action: ${past_action_visible}
#   abs_action: *abs_action
#   tqdm_interval_sec: 1.0
#   n_envs: 28
# evaluation at this config requires a 16 core 64GB instance.

dataset:
  _target_: diffusion_policy.dataset.High_Level_Heatmap_Train_Zarr_Sliced.HighLevelHeatmapTrain
  # episode_path: "/scratch/pbhowal/Diffusion_Policy_Training/Zarr_Trajectories/insert_onto_square_peg_WITH_LANGUAGE_EMBEDDINGS" #"/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/RVT2_GMM_Codebase/RVT2_Codebase/RVT_Backup_IDK/RVT/data_diffusion_policy/outputs_1st_insert_onto_square_peg/trajectories_data_FINAL_WITH_TEXT_EMBEDDING" #"/scratch/pbhowal/Diffusion_Policy_Training/Zarr_Trajectories/insert_onto_square_peg" #"/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/RVT2_GMM_Codebase/RVT2_Codebase/RVT_Backup_IDK/RVT/data_diffusion_policy/outputs_1st_insert_onto_square_peg/trajectories_data"
  base_dir : "/scratch/pbhowal/data_Diffusion_Policy_DEBUG" #"/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/RVT2_GMM_Codebase/RVT2_Codebase/RVT_Backup_IDK/RVT/data_diffusion_policy/" #outputs_1st_insert_onto_square_peg/trajectories_data" #"/scratch/pbhowal/Diffusion_Policy_Training/Zarr_Trajectories/insert_onto_square_peg_WITH_LANGUAGE_EMBEDDINGS/" #"/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/RVT2_GMM_Codebase/RVT2_Codebase/RVT_Backup_IDK/RVT/data_diffusion_policy/outputs_1st_insert_onto_square_peg/trajectories_data_FINAL_WITH_TEXT_EMBEDDING" #"/scratch/pbhowal/Diffusion_Policy_Training/Zarr_Trajectories/insert_onto_square_peg/" #"/project_data/held/pratik/run_sample_basic_experiments/Bimanual_Manipulation/RVT2_GMM_Codebase/RVT2_Codebase/RVT_Backup_IDK/RVT/data_diffusion_policy/outputs_1st_insert_onto_square_peg/trajectories_data"
  # tasks : ["close_jar",  "insert_onto_square_peg",  "light_bulb_in",  "meat_off_grill",  "open_drawer",  "place_shape_in_shape_sorter",  "place_wine_at_rack_location",  "reach_and_drag",  "slide_block_to_color_target", "stack_blocks"]
  # tasks: ["close_jar","open_drawer","push_buttons","reach_and_drag","insert_onto_square_peg","place_cups","put_groceries_in_cupboard","slide_block_to_color_target","light_bulb_in","place_shape_in_shape_sorter","put_item_in_drawer","stack_blocks","meat_off_grill","place_wine_at_rack_location","put_money_in_safe","sweep_to_dustpan_of_size"]
  # tasks: ["close_jar"]
  tasks: ["push_buttons"]
  early_fusion: True
  sequence_length: 16
  pad_before: 4
  pad_after: 4
  use_wrist_camera: True
  # _target_: diffusion_policy.dataset.robomimic_replay_image_dataset.RobomimicReplayImageDataset
  # shape_meta: *shape_meta
  # dataset_path: *dataset_path
  # horizon: ${horizon}
  # pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  # pad_after: ${eval:'${n_action_steps}-1'}
  # n_obs_steps: ${dataset_obs_steps}
  # abs_action: *abs_action
  # rotation_rep: 'rotation_6d'
  # use_legacy_normalizer: False
  # use_cache: True
  # seed: 42
  # val_ratio: 0.02
