#!/bin/bash

#SBATCH -N 1 # Number of nodes
#SBATCH -n 48
#SBATCH -p ROBO
#SBATCH --gpus=h100:4 #GPU specification. H100
#SBATCH -t 48:00:00 # Estimated time, 48hour max. DD-HH:MM.
#SBATCH --job-name 50-obj-act3d-mlp-low-level-with-goal-v_prediction # 50-obj-act3d-unet-low-level-with-goal
#SBATCH -o sbatch_output/job_%j.out
#SBATCH -e sbatch_output/job_%j.err
#SBATCH --mail-type=END
#SBATCH --mail-user=chialiak@andrew.cmu.edu


# use the bash shell
set -x 
# echo each command to standard out before running it


# ### first copy all the data needed in parallel
# # Define an array of source-destination pairs
source_dir="/jet/projects/cis240052p/ckuo1/dp3_demo"
declare -a SOURCES=(
    "${source_dir}/0702-obj-45448-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-46462-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-41510-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-46732-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-46801-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-46874-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-46922-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-46966-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-47570-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-47578-dense_pcd_on_goal:/local/"
    "${source_dir}/0702-obj-48700-dense_pcd_on_goal:/local/"    
    "${source_dir}/0705-obj-45526-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-45661-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-45694-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-45780-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-45910-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-45961-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-46408-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-46417-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-46440-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-46490-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-46762-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-46825-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-46893-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-47235-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-47281-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-47315-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-47529-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-47669-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-47944-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-48063-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-48177-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-48356-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-48623-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-48876-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-49025-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-49062-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-49132-dense_pcd_on_goal:/local/"
    "${source_dir}/0705-obj-49133-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-40417-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-41085-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-41452-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-45162-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-45176-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-45194-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-45203-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-45248-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-45271-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-45290-dense_pcd_on_goal:/local/"
    "${source_dir}/0712-obj-45305-dense_pcd_on_goal:/local/"
    # Add more source-destination pairs as needed
)

# Start the timer
SECONDS=0

# Function to run rsync command
run_rsync() {
    local src="$1"
    local dst="$2"
    rsync -az "$src" "$dst" &
}

# Loop through the array and run rsync commands in parallel
for pair in "${SOURCES[@]}"; do
    IFS=":" read -r src dst <<< "$pair"
    run_rsync "$src" "$dst"
done

# Wait for all background processes to complete
wait

echo "All rsync commands have completed."
total_time=$SECONDS
echo "Total time taken: $(($total_time / 60)) minutes and $(($total_time % 60)) seconds."

#### start training
singularity exec --bind /ocean/projects/cis240052p/ckuo1/RoboGen-sim2real:/mnt/RoboGen_sim2real/ --bind /local/:/local/ --nv /ocean/projects/cis240052p/ywang59/robogen-dp3-act3d.sif /mnt/RoboGen_sim2real/run-in-singularity-pickle-dense_gripper.sh
# singularity exec --bind /ocean/projects/cis240052p/ckuo1/RoboGen-sim2real:/mnt/RoboGen_sim2real/ --bind /local/:/local/ --nv /ocean/projects/cis240052p/ywang59/robogen-dp3-act3d.sif /mnt/RoboGen_sim2real/run-in-singularity-pickle-2.sh
# singularity exec --bind /ocean/projects/cis240052p/ckuo1/RoboGen-sim2real:/mnt/RoboGen_sim2real/ --bind /local/:/local/ --nv /ocean/projects/cis240052p/ywang59/robogen-dp3-act3d.sif /mnt/RoboGen_sim2real/run-in-singularity-pickle-3.sh
