name: hybrid

image_shape: &image_shape [3, 256, 256]
shape_meta: &shape_meta
  obs:
    cam0_image:
      shape: *image_shape
      type: rgb
    cam1_image:
      shape: *image_shape
      type: rgb
    cam2_image: # wrist camera
      shape: *image_shape
      type: rgb
    state:
      shape: [10]
      type: low_dim
    goal_gripper_pts:
      shape: [4, 3]
      type: goal_gripper
  action:
    shape: [10]

env_runner:
  _target_: diffusion_policy.env_runner.articubot_image_runner.ArticubotImageRunner
  n_train: 6
  n_train_vis: 2
  train_start_seed: 0
  n_test: 50
  n_test_vis: 4
  legacy_test: True
  test_start_seed: 100000
  max_steps: 300
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  fps: 10
  past_action: ${past_action_visible}
  n_envs: null
  observation_mode: image

dataset:
  _target_: diffusion_policy.dataset.lazy_articubot_dataset.LazyArticuBotDataset
  shape_meta: *shape_meta
  data_dir: outputs/All_Heatmap_Dataset/
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
  action_mode: ${action_mode}
